### ISSUE TITLE
Upstream custom components (nabu, media_player, ...) to esphome

### ISSUE THREAD

**Issue by flubshi** [esphome/home-assistant-voice-pe#230]
Hi there,

I am following this repo for a few months and I am very happy that you released the hardware this week :tada: Thanks for all the awesome work!

I noticed that you have created custom components and modified the original esphome components, e.g. *nabu*, *media_player*:

```
external_components:
  - source:
      type: git
      url: https://github.com/esphome/home-assistant-voice-pe
      ref: dev
    components:
      - aic3204
      - audio_dac
      - media_player
      - micro_wake_word
      - microphone
      - nabu
      - nabu_microphone
      - voice_assistant
      - voice_kit
    refresh: 0s
```

The nabu media player is awesome because it supports ducking and local files. I have embed these external components in my configuration files for a while.

Do you plan to upstream those new components and the other improvements to esphome?
