### ISSUE TITLE
Create sensor (or adjust existing) to recognize current audio output

### ISSUE THREAD

**Issue by malhalla** [esphome/home-assistant-voice-pe#239]
When Voice PE has a status other than idle i would mute my Media Player (eG Sonos) for the time Voice PE is talking. 

But the existing sensors go back to "idle" before audio output from Voice PE is finished.

**Comment by jackwilsdon** [comment]
The `assist_satellite` entity should be in state "responding" until it has finished responding (at least it is for me).

I use this automation to pause my TV when interacting with the Voice PE:

```yaml
alias: "Assist: pause TV on action"
description: ""
triggers:
  - trigger: state
    entity_id: assist_satellite.living_room_home_assistant_voice_assist_satellite
    from: idle
conditions:
  - condition: device
    device_id: 903ad7d4030876d2394d9e92ab5600df
    domain: media_player
    entity_id: 4134fcd48e39ad6c18e12c0729a8ca7d
    type: is_playing
actions:
  - action: media_player.media_pause
    metadata: {}
    data: {}
    target:
      device_id: 903ad7d4030876d2394d9e92ab5600df
  - wait_for_trigger:
      - trigger: state
        entity_id: assist_satellite.living_room_home_assistant_voice_assist_satellite
        to: idle
  - action: media_player.media_play
    metadata: {}
    data: {}
    target:
      device_id: 903ad7d4030876d2394d9e92ab5600df
mode: single
```
