### ISSUE TITLE
Feature Request: Option to Disable LED Indicators for Mute and Microphone at Night

### ISSUE THREAD

**Issue by highTowerSU** [esphome/home-assistant-voice-pe#267]
Currently, the LED indicators for mute and microphone status remain illuminated during the night. While this is useful during the day, it can be disruptive in dark environments, such as bedrooms. An option to automatically disable or dim these LEDs during specified hours (e.g., night mode) would significantly improve the user experience.

Proposed Solution:

Introduce a "Night Mode" or "LED Control" feature in the settings that allows users to:

1. Schedule a time range when the LEDs should be turned off or dimmed.

2. Manually toggle the LED indicators for mute and microphone.

3. Optionally adjust the brightness of the LEDs for less intrusive lighting.

Benefits:

Improved user comfort, especially in dark environments.

Enhanced flexibility and customization for users.

Potentially reduced energy consumption.

Use Case:

A user places the device in their bedroom and prefers a completely dark environment while sleeping. With this feature, they could schedule the LEDs to turn off between 10 PM and 7 AM, ensuring an uninterrupted night's sleep.

**Comment by jackwilsdon** [comment]
It would be nice to have a separate brightness slider for the light. I'm currently using this script as a workaround:

```yaml
sequence:
  - variables:
      mute_entity_id: |
        {% for entity_id in device_entities(device) %}
          {% if entity_id.startswith("switch.") and entity_id.endswith("_mute") %}
            {{ entity_id }}
          {% endif %}
        {% endfor %}
      light_entity_id: |
        {% for entity_id in device_entities(device) %}
          {% if entity_id.startswith("light.") %}
            {{ entity_id }}
          {% endif %}
        {% endfor %}
          
    alias: Get entities
  - variables:
      was_muted: "{{ states(mute_entity_id) == \"on\" }}"
      was_lit: "{{ states(light_entity_id) == \"on\" }}"
    alias: Get state
  - alias: Unmute if muted
    if:
      - condition: template
        value_template: "{{ was_muted }}"
    then:
      - action: switch.turn_off
        metadata: {}
        data:
          entity_id: "{{ mute_entity_id }}"
      - delay:
          hours: 0
          minutes: 0
          seconds: 0.5
  - action: light.turn_on
    data:
      brightness: "{{ brightness }}"
      entity_id: "{{ light_entity_id }}"
    alias: Turn on light
  - if:
      - condition: template
        value_template: "{{ not was_lit }}"
    then:
      - action: light.turn_off
        data:
          entity_id: "{{ light_entity_id }}"
    alias: Turn off if previously unlit
  - alias: Mute if previously muted
    if:
      - condition: template
        value_template: "{{ was_muted }}"
    then:
      - action: switch.turn_on
        metadata: {}
        data:
          entity_id: "{{ mute_entity_id }}"
alias: Set assist brightness
description: ""
fields:
  device:
    selector:
      device: {}
    name: Device
    required: true
  brightness:
    selector:
      number:
        min: 1
        max: 255
    name: Brightness
    required: true

```

It's a bit of a pain as changing brightness whilst muted doesn't actually work (seems like a bug?), so the script unmutes (if previously muted), changes the brightness and then remutes (if previously muted). Thankfully turning the light on and off again quickly like this doesn't cause it to flash unless it was already on.

**Comment by SpencerDub** [comment]
I just posted a question about this very thing on the HA forums.

I would greatly appreciate this feature, for exactly the reasons you outline. I'd like a Voice PE in my bedroom; I'd also like it to be fully muted _and_ dark when I'm sleeping.

**Comment by unreturnable** [comment]
👍🏻 for this feature. We have one of the preview edition devices we want to just use as a smart speaker in a bedroom in our house. So we want to be able to have the mute continuously turned on for that device but not have the red led on while sleeping.

Turning the device upside down is my current workaround for this without having to add scripts that would break updates. It feels  a bit rubbish though as a solution.

**Comment by thewan056** [comment]
Call it DND or Do Not Disturb toggle, and allow the user to toggle one switch where, in addition to the above suggestions of scheduling lighting and muting the mic, also control the volume or mute the sound output too. 
Just in case. We want a good nights sleep with a peace of mind that it doesn't light up, doesn't listen and doesn't make noise too.

**Comment by KostaMadorsky** [comment]
Are there any plans to implement this anytime soon?
Considering getting 3 devices (1 for living/kitchen and 2 for bedrooms).

**Comment by pedrogarrett** [comment]
Yes please! My wife refuses to have this in the bedroom if we can't guarantee the led will stay off at night.

It flashes bright red if connection is lost, and I'd really like to be able to disable that.

**Comment by KostaMadorsky** [comment]
As long as there is a toggle to turn off the light we can easily setup automations to implement do not disturb mode ourselves. 

I am already muting it when everyone is away and changing the volume during the day. But there is no setting to turn off the light.

**Comment by KostaMadorsky** [comment]
As a workaround, I am currently setting LED ring brightness to 1% during night with an automation.
It's not too bad, but still emits a bit of light. In fact, it cannot go below 16% brightness.

Currently, when the LED toggle is enabled, it turns on the light permanently (I guess so we can see the light while configuring the colour/brightness). So additional toggle to enable/disable LED during normal operations would be helpful.

![Image](https://github.com/user-attachments/assets/12b35a6f-c8f8-405b-a552-63246a95b56a)

![Image](https://github.com/user-attachments/assets/194e4940-e014-472d-9dc3-8dd6a0bc7067)

**Comment by KostaMadorsky** [comment]
I might just put a smart plug for the voice device in the bedroom and schedule it to turn off during the night...

**Comment by StephenAOSP** [comment]
I got chat got to write me a bit of code that seems to work well.   

```
interval:
  - interval: 1ms
    then:
      - light.turn_off: voice_assistant_leds
```

Drop this into your ESPHome config yaml anywhere after your package is defined.  You can sometimes get the briefest of flash from the light, but minimal.  

I dont know if you can remove the interval section completely and just have light.turn off.  But it seems to work quite well in testing

Edit all though it works, It generates thousands and thousands of lines of logs.  I wouldn't want to use it long term

**Comment by apriendeau** [comment]
There needs to be a way to lower the ring lights or turn off completly when listening because we have migraine sensitive and light sensitive people in the house and it's blinding when it's listening at night.

**Comment by itpropro** [comment]
Is this still not fixed? The home assistant voice feels like an echo dot from 5 years ago with how little you can configure and how bad it works currently…

**Comment by KostaMadorsky** [comment]
You can configure the LED's colour and brightness however you want @apriendeau 
I have an automation that changes the brightness during the day.

For bedrooms, I have it set to purpleish around 17%, and it's barely visible in a pitch-black room.

1. Go to your Voice PE ESPHome device in HA
2. Turn on the LED Ring (one of the entities, not sure what the original name was)
3. Configure it the way you want
4. Turn it off
5. Trigger Voice PE and see if it works

<img width="629" height="714" alt="Image" src="https://github.com/user-attachments/assets/1f798184-8440-46e3-ac43-57b51ac28562" />

**Comment by itpropro** [comment]
> You can configure the LED's colour and brightness however you want [@apriendeau](https://github.com/apriendeau) I have an automation that changes the brightness during the day.
> 
> For bedrooms, I have it set to purpleish around 17%, and it's barely visible in a pitch-black room.
> 
> 1. Go to your Voice PE ESPHome device in HA
> 2. Turn on the LED Ring (one of the entities, not sure what the original name was)
> 3. Configure it the way you want
> 4. Turn it off
> 5. Trigger Voice PE and see if it works
> 
> <img alt="Image" width="629" height="714" src="https://private-user-images.githubusercontent.com/9411729/546507098-1f798184-8440-46e3-ac43-57b51ac28562.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA2NjIyMTksIm5iZiI6MTc3MDY2MTkxOSwicGF0aCI6Ii85NDExNzI5LzU0NjUwNzA5OC0xZjc5ODE4NC04NDQwLTQ2ZTMtYWM0My01N2I1MWFjMjg1NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAyMDlUMTgzMTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhlYjU1ODdiNTc2OGNkZDc5Y2Q2N2IxYTgxNjc4ODE1MzUwMzQ4NWM2ZmU3NzVmYTE3ZDEwZmNjNGJlM2RhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._IN2p0mDeZLNbTqt5GbS2bBRXhzClhTgXey_i3j4lYM">

Thanks for this, this should be documented much better and is very unintuitive, but at least it’s possible. I am still searching for a way to make it time dependent, but I will just trigger a time based automation to change the light setting.

**Comment by KostaMadorsky** [comment]
> I am still searching for a way to make it time dependent

Yeah, you just make time-based automation. I just have 2 simple automations for the evening to reduce brightness and the morning to increase.

If you have a light sensor in the room, you can use that too (e.g. when low light, reduce the brightness of the ring).

**Comment by vebivex** [comment]
I've used the following to override the master microphone switch, so the red leds aren't on. This forces the normal behavior for the leds.

```
script:
- id: !extend control_leds_muted_or_silent
  then:
    - light.turn_off: voice_assistant_leds
    - if:
        condition:
          light.is_on: led_ring
        then:
          light.turn_on: led_ring
```

Take control with ESPHome, add this to the end of the yaml. You could also override other leds that way, or add a setting for it using the same yaml as from the github. 

It'd be great if this would be a default feature though, you should be able to select an option for the leds like "default", "mute off", "always off".
