### ISSUE TITLE
After play sounds nothing else happens

### ISSUE THREAD

**Issue by enx1998** [esphome/home-assistant-voice-pe#309]
I have a HAVPE with firmware version 25.1.0 (ESPHome 2024.12.2), and too often the device recognises the wake word, plays the sound, but nothing else happens: the ring stays off, and the voice recognition doesn't start.
This is what happens

![Image](https://github.com/user-attachments/assets/eb7e87b2-f689-4d99-b320-74a068978bb3)

Is there anything can I do?

Thanks, ENx

**Comment by BelenCaSa** [comment]
Hello
Same here, it usually happens more often after a period of inactivity. That is, once the device responds, you call it again and it responds again, however, in the mornings it gets "stuck", you have to call it at least three or four times for it to activate.

**Comment by StrandmonYellow** [comment]
I saw some of this behavior also since updating a few days ago. It seems to also react less often to the wake word.

**Comment by enx1998** [comment]
> I saw some of this behavior also since updating a few days ago. It seems to also react less often to the wake word.

@StrandmonYellow what firmware version do you have installed on the device?

**Comment by BelenCaSa** [comment]
![Image](https://github.com/user-attachments/assets/b8dc2e29-ec2a-46d7-801a-2ef2da010fac)

**Comment by enx1998** [comment]
OK, I have taken control of HAVPE and I see this error:

[E][voice_assistant:776]: Error: duplicate_wake_up_detected - Duplicate wake-up detected for Okay Nabu

Same issue here: https://github.com/esphome/issues/issues/5887

Is it possible to fix this error?

Thank you

**Comment by StrandmonYellow** [comment]
@enx1998 I am running the version as shown below:

![Image](https://github.com/user-attachments/assets/b1df9f25-5b8d-4d17-8478-9018c712d562)

However, I don't think this is correct because I have the restart button showing with my device, and this was added in a newer release than what is showing.

**Comment by eikel** [comment]
I observe the same with a Home Assistant Voice PE since I have it (firmware currently at 25.3.0 (ESPHome 2025.2.0)). Raw pipeline output of a failure:
```yaml
stage: done
run:
  pipeline: 01jhwqkwt8s7dc64eqzfrfwcyb
  language: de
  conversation_id: 01JNVT6BFWWP757MVMWQ7D2GX8
events:
  - type: run-start
    data:
      pipeline: 01jhwqkwt8s7dc64eqzfrfwcyb
      language: de
      conversation_id: 01JNVT6BFWWP757MVMWQ7D2GX8
    timestamp: "2025-03-08T21:25:37.870296+00:00"
  - type: error
    data:
      code: duplicate_wake_up_detected
      message: Duplicate wake-up detected for Okay Nabu
    timestamp: "2025-03-08T21:25:37.870645+00:00"
  - type: run-end
    data: null
    timestamp: "2025-03-08T21:25:37.871023+00:00"
error:
  code: duplicate_wake_up_detected
  message: Duplicate wake-up detected for Okay Nabu
```
I also have a M5Stack Atom Echo (firmware currently at 25.2.1 (ESPHome 2025.2.0)) and never experienced the problem there.
