### ISSUE TITLE
[REQUEST] Support choosing response media_player in config

### ISSUE THREAD

**Issue by Ramblurr** [esphome/home-assistant-voice-pe#320]
Note: this is not a duplicate of [issue 316](https://github.com/esphome/home-assistant-voice-pe/issues/316). Issue 316 is about using the AUX/3.5mm audio out on the PE for music and the builtin speaker for Assist's response.

This request is about configuring the PE such that the TTS response Assist generates can be configured to go to a different media_player entity entirely.

Apparently this is already possible for those building custom esphome voice satellites by specifing `voice_assistant.on_tts_end` in the esphome config.

- https://community.home-assistant.io/t/year-of-the-voice-chapter-5/655319/25
- https://community.home-assistant.io/t/voice-assistant-have-assistant-reply-on-a-different-media-player/625875/6

**Comment by BlackandBlue1908** [comment]
+1

**Comment by kosmaluk** [comment]
Popieram. Funkcja wyboru media playera do ogłaszania odpowiedzi jest bardzo pożądana

**Comment by kosmaluk** [comment]
you can easily take over the code and make changes without losing the ability to update. A new Home Assistant Voice Firmware update sensor has been added. You can add your own media_player or create start/stop wakeword buttons and in automations make a continuation of the conversation, dialogflow, etc.

**Comment by Ramblurr** [comment]
> you can easily take over the code and make changes without losing the ability to update

Can you describe how to do this? It isn't obvious to me. The PE doesn't show up in esphome builder.

**Comment by kosmaluk** [comment]
You need to enable TAKE CONTROL and install the device in Esp Builder. If you don't see it, enable the three dots at the top and "show discovered devices". After installing, you can add any elements you are interested in to the section. For example, mediaplayer or other commands that you will use in automations

`on_tts_end:
     - homeassistant.service:
         service: media_player.play_media
         data:
           entity_id: media_player.google_home_mini # <- change this
           media_content_id: !lambda 'return x;'
           media_content_type: music
           announce: "true"`

**Comment by phila-dot** [comment]
Have you successfully done this or just assuming because it works with the older VA’s?

I keep seeing people post this, but it doesn’t work with the VA PE nor the new build  S3 Box. There is nothing returned, so you get no tts audio.

**Comment by kosmaluk** [comment]
If I write a solution, it means I did it and it works. Why wouldn't it work? The documentation for ESPHome is the same and applies to all these devices

https://esphome.io/components/voice_assistant.html 

You have to Adopt a device and adapt the code. The examples that are on the forums work perfectly.

I have collected various solutions and together with ChatGpt I have implemented the solutions that I wanted. I have done, among others:
1. Sending sound TTS to another media player
2. Question and answer sensors (I use them to debug STT operation and automation to continue the conversation without waking up again)
3. START and STOP wake word buttons, which I also use for these automations

Everything works great.

Everyone got scared by the entry in the documentation not to take control and are waiting for new functions.

In the movie Chapter 9 they said that they added a new Firmware update sensor which you would normally use to update the device after taking over the code

![Image](https://github.com/user-attachments/assets/6778fea0-16e8-4231-8b0d-1af250b429cc)

![Image](https://github.com/user-attachments/assets/11b084c3-deed-444c-8c9e-702d8b86c448)

![Image](https://github.com/user-attachments/assets/7a2ee169-e8a5-47fe-8db7-0d6457c7adf7)

**Comment by Ramblurr** [comment]
> You need to enable TAKE CONTROL

That's the bit I can't find. I have seen other people mention that. But I can't find that option anywhere. Where in HA is a "take control" button?

**Comment by kosmaluk** [comment]
something is wrong with your eyesight :).
I wrote how to do it a few posts above :)
ESP Builder --- enable the three dots at the top and "show discovered devices".  HAVPE will show up and click ADOPT

**Comment by Ramblurr** [comment]
> something is wrong with your eyesight :).
> I wrote how to do it a few posts above :)

I saw what you wrote, but that post don't contain the string "take control", so I assumed that entire post was for after you "took control". 

I appreciate your assistance here by the way.



> ESP Builder --- enable the three dots at the top and "show discovered devices". HAVPE will show up and click ADOPT

Ok, now we are getting somewhere, the actual button is "show discovered devices" and then "adopt", not "take control". I appreciate the exact instructions.

However, when I click "Show discovered devices", nothing happens (except now the button says "Hide discovered devices". The list of esp devices remains the same, and its just my own custom devices.

Presumably this is because my IOT devices and HA are on different vlans. Is there a way to import it manually without relying on MDNS?

Edit: I managed to do this myself, I simple created the yaml config I wanted, and ensured the `wifi.manual_ip` component config was set to the static ip of my existing Voice PE device, then installed it using esphome builder. Pretty straightforward. I copied `https://github.com/esphome/home-assistant-voice-pe/blob/ba4fca5344724d56b586f7ea9173e0cb2db2773f/home-assistant-voice.factory.yaml` as the base yaml, and then added my wifi overrides.

I still think that is feature request stands however, as this should be possible to configure without having to edit esphome firmware.

**Comment by itispip** [comment]
> Everyone got scared by the entry in the documentation not to take control and are waiting for new functions.

Exaclty, that's my fear. Even "taking control" is easy, and ESPHome added a new Firmware update sensor, but what I'm afraid is update new official firmware will need back to factory firmware first, then update, then ESP take control again, and then customize/add the sections not available in factory firmware again --- that can be a repeated pain.

**Comment by kosmaluk** [comment]
I don't know, but I updated the device to 2025.2 and it went without a problem and my configuration remained. We'll see how they implement some new functions or elements or add them

![Image](https://github.com/user-attachments/assets/c5c1f482-9582-4642-91e8-6a5da4ce23ee)

**Comment by ev1502** [comment]
> If I write a solution, it means I did it and it works. Why wouldn't it work? The documentation for ESPHome is the same and applies to all these devices
> 
> https://esphome.io/components/voice_assistant.html
> 
> You have to Adopt a device and adapt the code. The examples that are on the forums work perfectly.
> 
> I have collected various solutions and together with ChatGpt I have implemented the solutions that I wanted. I have done, among others:
> 
> 1. Sending sound TTS to another media player
> 2. Question and answer sensors (I use them to debug STT operation and automation to continue the conversation without waking up again)
> 3. START and STOP wake word buttons, which I also use for these automations
> 
> Everything works great.
> 
> Everyone got scared by the entry in the documentation not to take control and are waiting for new functions.
> 
> In the movie Chapter 9 they said that they added a new Firmware update sensor which you would normally use to update the device after taking over the code
> 
> ![Image](https://github.com/user-attachments/assets/6778fea0-16e8-4231-8b0d-1af250b429cc)
> 
> ![Image](https://github.com/user-attachments/assets/11b084c3-deed-444c-8c9e-702d8b86c448)
> 
> ![Image](https://github.com/user-attachments/assets/7a2ee169-e8a5-47fe-8db7-0d6457c7adf7)

Thank you for posting screenshots, are you by chance able to upload to upload your full configuration file so we can see all the details of the progress you've made?

**Comment by Ramblurr** [comment]
Here is my  esphome config for my Voice PE. Note I've changed from calling `media_player.play_media` for the TTS audio to doing instead `assist_satellite.announce`. 

This is because I have one Voice PE that I want to act as *only* a microphone (that's the one the config below is for). Then I have a linux computer running a [wyoming-satellite](https://github.com/rhasspy/wyoming-satellite) which is plugged into my whole home audio streaming system with a [hardware ducker](https://rolls.com/product/DU30b). 

This lets me speak into the Voice PE, but hear the TTS replies over my built-in wall speakers.

You have to be running 2025.7.3 at least

```yaml

...normal api/wifi/logging/etc that is in every esphome device is omitted...

packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml@dev

voice_assistant:
  id: va
  media_player: !remove
  on_tts_start:
    then:
      - logger.log: "on_tts_start-start"
      - homeassistant.action:
          action: assist_satellite.announce
          data:
            entity_id: assist_satellite.my_satellite
            message: !lambda 'return x;'
      - logger.log: "on_tts_start-end"
  # or, if you want to use media_player.play_media...
  # on_tts_end:
  #   - logger.log: "on_tts_end-start"
  #   - homeassistant.action:
  #       action: media_player.play_media
  #       data:
  #         entity_id: media_player.your_player
  #         media_content_id: !lambda 'return x;'
  #         media_content_type: music
  #         announce: "false"
```

**Comment by lextiz** [comment]
Thanks for opening this. This is exactly what I am trying to figure out before building a PoC.

My setup would be Voice PE as mic / wake-word only, with replies played through a normal HA `media_player` (Sonos first, but ideally generic). I am also hoping continuous conversation can still work, so HA would need some reasonable way to know when the external speaker has finished before listening again.

The `on_tts_end` YAML workaround is useful, but I would rather not take over the firmware if the right fix belongs in HA / `assist_satellite`.

Do maintainers see this as a Voice PE firmware option, or should this be proposed in HA Core as an `assist_satellite` response output target?

**Comment by dcybeldesign** [comment]
Same conclusion as the linked discussion (home-assistant/discussions#689): this needs firmware-level changes to separate capture and reply, not something fixable from outside the Voice PE.

For anyone landing here who mainly wants scripted announcements (not live conversational replies) routed to a Bluetooth speaker specifically, I built an add-on that exposes any Bluetooth speaker as a native media_player entity in HA: https://github.com/dcybeldesign/ha-mpd-bluetooth-bridge. Works with `tts.speak`/automations today, doesn't touch the core ask here.

**Comment by limitless-code** [comment]
Hello, I needed a work around to output audio to a BT speaker (or any supported media player) as self-signed certificates are broken on later VPE firmware.

I have a working -ish solution where I use a helper selector to choose which "media_player" to output audio to and have some script in the ESPhome yaml config for the VPE that takes that media_player value at boot and also allows to choose the media_player on the fly. 

You will need to expose your e.g Bluetooth speaker as a media_player entity in HA using an add-on like the one @dcybeldesign commented on. You will also need to "take control" or "Adopt" your VPE in order to tailor the config below to your setup, once you have done this all firmware updates (to your adopted device) are performed via espHome builder.

Here is the espHome VPE yaml config:

```
substitutions:
  name: home-assistant-voice-xxxx
  friendly_name: Small Bedroom assistant
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
esp32:
  board: esp32-s3-devkitc-1
  toolchain: esp-idf
  framework:
    type: esp-idf
http_request:
  verify_ssl: true
  ca_certificate_path: rootCA.crt
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  on_boot:
    priority: -100
    then:
      - lambda: |-
          ESP_LOGI("main", "System booted. Waiting for Home Assistant text sensor synchronization...");

# --- GLOBALS ---
globals:
  - id: route_to_external_speaker
    type: bool
    initial_value: 'false'
    restore_value: yes # Remembers the routing state across restarts
  - id: chosen_speaker
    type: std::string
    initial_value: '""'
    restore_value: yes # Permanently stores the entity string in memory

# --- TEXT SENSORS ---
text_sensor:
  - platform: homeassistant
    id: helper_selector_state
    entity_id: input_select.house_audio_source
    internal: false 
    # Automatically triggers at boot connection AND whenever the dropdown updates
    on_value:
      then:
        - lambda: |-
            id(chosen_speaker) = x;
            if (x.rfind("media_player.", 0) == 0) {
              id(route_to_external_speaker) = true;
              ESP_LOGD("main", "Routing updated: EXTERNAL SPEAKER ACTIVE (%s)", x.c_str());
            } else {
              id(route_to_external_speaker) = false;
              ESP_LOGD("main", "Routing updated: LOCAL SPEAKER ACTIVE");
            }

# --- API SERVICES ---
api:
  encryption:
    key: xxxxx
  actions:
    - action: update_audio_target
      variables:
        selected_target: string
      then:
        - lambda: |-
            id(chosen_speaker) = selected_target;
            if (selected_target.find("media_player.") == 0) {
              id(route_to_external_speaker) = true;
              ESP_LOGD("main", "ESPHome Routing Flag updated: EXTERNAL SPEAKER MODE ACTIVE (%s)", selected_target.c_str());
            } else {
              id(route_to_external_speaker) = false;
              ESP_LOGD("main", "ESPHome Routing Flag updated: LOCAL SPEAKER MODE ACTIVE");
            }

# --- VOICE ASSISTANT CONTROL ---
voice_assistant:
  id: va
  # (Your existing mic and hardware settings stay here)
  
  on_tts_start:
    - if:
        condition:
          lambda: 'return id(route_to_external_speaker);'
        then:
          - homeassistant.event:
              event: esphome.voice_pe_tts_redirect
              data:
                text: !lambda 'return x;'
                target_entity: !lambda 'return id(chosen_speaker);'
       
          - delay: 200ms
          - voice_assistant.stop
 ```
This is the helper selector that `text_sensor` uses in the above espHome VPE config:

```
entity_id: input_select.house_audio_source
state: media_player.nux_mighty_bt_speaker_85b1ecde_sendspin_bt_bridge_rc
last_changed: '2026-09-09T20:44:31.768Z'
last_updated: '2026-09-09T22:34:58.282Z'
attributes:
  options:
    - media_player.nux_mighty_bt_speaker_xxx_sendspin_bt_bridge_rc
    - media_player.small_bedroom_assistant_media_player
    - media_player.home_assistant_voice_xxxx_media_player
    - media_player.living_room_tv_2
  editable: true
  icon: mdi:audio-input-stereo-minijack
  friendly_name: Audio_Source
```
I am unable to test TTS to the VPE itself as self-signed certificates are currently broken. I believe a fix is imminent for this.

https://github.com/esphome/backlog/issues/129

TTS automation :
```
alias: 'Voice PE: Redirect Audio Stream'
description: >-
  Catches the network event from ESPHome and routes the text to the selected
  speaker
triggers:
  - event_type: esphome.voice_pe_tts_redirect
    trigger: event
conditions: []
actions:
  - target:
      entity_id: tts.piper
    data:
      media_player_entity_id: '  {{ (media_player_id) }} '
      message: '{{ trigger.event.data.text }}'
    action: tts.speak
mode: queued
max: 10
variables:
  media_player_id: '{{ trigger.event.data.target_entity }}'
```

Radio player automation(this is not the full automation as it's too long, below is a snippet don't know if it will work through copy and paste, certainly each media_player.player_media media content URL will be different in your music assistant instance. For more information on radio player see https://community.home-assistant.io/t/how-to-play-radio-channel-on-home-assistant-voice-media-player/816326/9?u=csp170):

```
alias: Radio Player
description: ''
triggers:
  - trigger: conversation
      command:
        - '[Clay] [Play] [Plays] [Radio] Caprice'
      id: Radio Caprice
actions:
  - variables:
      audio_output_target: '{{ states(''input_select.house_audio_source'') }}'
  - action: input_button.press
    metadata: {}
    target:
      entity_id: input_button.check_music_assistant
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
      - condition: state
        entity_id: binary_sensor.music_assistant_addon_running
        state:
          - 'off'
          - unavailable
          - unknown
    then:
      - action: assist_satellite.ask_question
        metadata: {}
        data:
          question: Would you like to start music assistant?
          preannounce: true
          answers:
            - id: MA_START
              sentences:
                - 'yes'
                - 'no'
          entity_id: ' {{ assist_satellite_device }} '
        response_variable: music_assistant_startup
      - if:
          - condition: template
            value_template: '{{ ''yes'' in music_assistant_startup.sentence }}'
        then:
          - action: hassio.addon_start
            metadata: {}
            data:
              addon: d5369777_music_assistant_beta
          - set_conversation_response: Starting music assistant
          - action: assist_satellite.announce
            metadata: {}
            target:
              entity_id: '  {{ assist_satellite_device }} '
            data:
              message: Starting music assistant
              preannounce: false
          - repeat:
              until:
                - condition: template
                  value_template: >-
                    {{is_state("binary_sensor.music_assistant_addon_running",
                    "on")}}
              sequence:
                - action: input_button.press
                  metadata: {}
                  target:
                    entity_id: input_button.check_music_assistant
                  data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 15
          milliseconds: 0
  - choose:
        - conditions:
          - condition: trigger
            id:
              - Trance
        sequence:
          - action: media_player.play_media
            metadata: {}
            target:
              entity_id: '  {{ (voice_assistant_device) }} '
            data:
              media:
                media_content_id: library://radio/13
                media_content_type: music
                metadata:
                  title: 90s90s Trance
                  thumbnail: null
                  media_class: music
                  children_media_class: null
                  navigateIds:
                    - {}
                    - media_content_type: music_assistant
                      media_content_id: radio
                  browse_entity_id: media_player.dining_room_assistant_media_player
              announce: false
          - set_conversation_response: 

variables:
  audio_output_target: '{{ states(''input_select.house_audio_source'') }}'
  voice_assistant_device: ' {{ (audio_output_target) }} '
     media_player_id: ' {{ trigger.device_id }} '
  media_player: ' {{ device_entities(media_player_id) |select(''search'',''^media_player.'')|first }} '
  friendly_name: ' {{ states[media_player][''attributes''][''friendly_name''] }} '
  media_player_redact: ' {{ (media_player) | regex_replace(find=''media_player'', replace='''', ignorecase=False) }} '
  prepend1: media_player.
  voice_assistant_device-old: ' {{ prepend1 ~ (friendly_name) | slugify }} '
  prepend2: assist_satellite
  assist_satellite_device: ' {{ trigger.satellite_id }} '
mode: parallel
max: 3
```
Below is the media_player controller for volume/player/ pause etc.

```
alias: Voice assistant controls
description: ''
triggers:
  - trigger: conversation
    command:
      - (stop|top|shut up)
      - Top [playing] [media] [player]
      - Stop [playing] [media] [player]
    id: Stop
  - trigger: conversation
    command:
      - Pause [(media|player)]
    id: Pause
  - trigger: conversation
    command:
      - '[Set] (volume|sound) [to] (1|5|10|15|20|30|40|50|60|70|80|90|100)'
    id: Volume
    variables:
      volume_level_sentence: ' {{ trigger.sentence }} '
      volume_level: ' {{ (volume_level_sentence) |regex_findall(''\d+'')|first|int|multiply(0.01) }} '
      volume: ' {{ (volume_level) }} '
  - trigger: conversation
    command:
      - (Mute|nute)
    id: mute
  - trigger: conversation
    command:
      - (unmute|unnute)
    id: unmute
  - trigger: conversation
    command:
      - (start)
    id: Start
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Stop
        sequence:
          - action: media_player.media_stop
            metadata: {}
            data: {}
            target:
              entity_id: ' {{ (voice_assistant_device) }} '
      - conditions:
          - condition: trigger
            id:
              - Pause
        sequence:
          - action: media_player.media_pause
            metadata: {}
            data: {}
            target:
              entity_id: ' {{ (voice_assistant_device) }} '
      - conditions:
          - condition: trigger
            id:
              - Volume
        sequence:
          - action: media_player.volume_set
            metadata: {}
            data:
              volume_level: ' {{ (volume) }} '
            target:
              entity_id: ' {{ (voice_assistant_device) }}  '
            enabled: true
      - conditions:
          - condition: trigger
            id:
              - mute
        sequence:
          - action: media_player.volume_mute
            metadata: {}
            data:
              is_volume_muted: true
            target:
              entity_id: ' {{ (voice_assistant_device) }} '
            enabled: true
      - conditions:
          - condition: trigger
            id:
              - unmute
        sequence:
          - action: media_player.volume_mute
            metadata: {}
            data:
              is_volume_muted: false
            target:
              entity_id: ' {{ (voice_assistant_device) }} '
            enabled: true
      - conditions:
          - condition: trigger
            id:
              - Start
        sequence:
          - action: media_player.media_play
            metadata: {}
            target:
              entity_id: ' {{ (voice_assistant_device) }} '
            data: {}
variables:
  media_player_id: ' {{ trigger.device_id }} '
  media_player: ' {{ device_entities(media_player_id) |select(''search'',''^media_player.'')|first }} '
  friendly_name: ' {{ states[media_player][''attributes''][''friendly_name''] }} '
  prepend: media_player.
  voice_assistant_device-old: ' {{ prepend ~ (friendly_name) | slugify}} '
  audio_output_target: '{{ states(''input_select.house_audio_source'') }}'
  voice_assistant_device: ' {{ (audio_output_target) }} '
mode: parallel
max: 5
```
