### ISSUE TITLE
Play multiple TTS voice messages one after the other.

### ISSUE THREAD

**Issue by Morpheus2018** [esphome/home-assistant-voice-pe#323]
**Currently only the last TTS in the list is played**. Multiple TTS voice messages should be played one after the other.

can someone tell me how to play multiple TTS on Home Assistant Voice one after the other? In the following examples (example.1) only the last TTS is played, (example.2) only the conversation answer "okay" is played. Does it depend on the hardware or the script?

example 1:
```
alias: Test Voice
sequence:
  - action: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.home_assistant_voice_09c43e_media_player
      message: test nachricht
    target:
      entity_id: tts.home_assistant_cloud
  - action: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.home_assistant_voice_09c43e_media_player
      message: test nachricht 2
    target:
      entity_id: tts.home_assistant_cloud
mode: single
```

In this example the TTS is skipped completely: 

```
alias: Voice Test
description: ""
triggers:
  - alias: Test
    trigger: conversation
    command:
      - test
    id: test
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - test
        sequence:
          - action: tts.speak
            data:
              cache: true
              media_player_entity_id: media_player.home_assistant_voice_09c43e_media_player
              message: test nachricht
            target:
              entity_id: tts.home_assistant_cloud
            enabled: true
          - action: tts.speak
            data:
              cache: true
              media_player_entity_id: media_player.home_assistant_voice_09c43e_media_player
              message: test nachricht 2
            target:
              entity_id: tts.home_assistant_cloud
            enabled: true
          - set_conversation_response: okay
            enabled: true
        alias: Test
mode: single
```

please program cash, queue or memory

**Comment by Morpheus2018** [comment]
There is an unknown to me "action: assist_satellite.announce" that allows messages to be played one after the other!

```
alias: Test Voice
sequence:
  - action: assist_satellite.announce
    metadata: {}
    data:
      message: test
    target:
      entity_id: assist_satellite.home_assistant_voice_09c43e_assist_satellit
  - action: assist_satellite.announce
    metadata: {}
    data:
      message: test 2
    target:
      entity_id: assist_satellite.home_assistant_voice_09c43e_assist_satellit
  - action: assist_satellite.announce
    metadata: {}
    data:
      message: test 3
    target:
      entity_id: assist_satellite.home_assistant_voice_09c43e_assist_satellit
mode: single
icon: mdi:test-tube

```
