### ISSUE TITLE
Could not find __init__.py file for component aic3204.

### ISSUE THREAD

**Issue by Rep-Hueman** [esphome/home-assistant-voice-pe#328]
Error ESP Home on update voice pe
```
INFO ESPHome 2025.2.0
INFO Reading configuration /config/esphome/home-assistant-voice-096399.yaml...
INFO Updating https://github.com/esphome/home-assistant-voice-pe@dev
Failed config

external_components: [source /data/packages/dc43710d/home-assistant-voice.yaml:1507]
  - source: 
      type: git
      url: https://github.com/esphome/home-assistant-voice-pe
      ref: dev
    components: 
      
      Could not find __init__.py file for component aic3204. Please check the component is defined by this source (search path: /data/external_components/3bf38338/esphome/components/aic3204/__init__.py).
      - aic3204
      - audio_dac
      - media_player
      - micro_wake_word
      - microphone
      - nabu
      - nabu_microphone
	  
```

Config:

```
substitutions:
  name: home-assistant-voice-096399
  friendly_name: Home Assistant Voice 2
  ha_voice_02_version: "25.02.19"
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: I3EU5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

text_sensor:
  # WiFi info
  - platform: wifi_info
    ip_address:
      name: "IP address"
      icon: "mdi:network-outline"
    ssid:
      name: "Connected SSID"
    bssid:
      name: "Connected BSSID"
    mac_address:
      name: Mac Wifi Address
  # M5Stack Information
  - platform: template
    id: text_sensor_ha_voice_02_version
    name: "Software Version"
    update_interval: 5h
    lambda: |-
      return {"${ha_voice_02_version}"};  

```
