### ISSUE TITLE
[Feature request] Expose separate volume levels for assist and media playback

### ISSUE THREAD

**Issue by mjbogusz** [esphome/home-assistant-voice-pe#369]
Just like the title states - it'd be great to have the volume level for voice assist exposed independently from media playback volume.

Right now if VoicePE is used e.g. as a background music player and thus its volume level is set low, the voice assist feedback volume is also very low.

As assist's volume should be more of a set and forget type of setting, I think the volume knob should adjust only media playback's volume level; optionally, rotating the knob while holding the main button could adjust the assist's volume, but that's for bonus points.

Having a quick skim through the configuration file and esphome's components documentation, I think it would either require either splitting out the `announcement_resampling_speaker` to a separate `media_player` instance (which might not be as easy as it sounds) or adding per-pipeline volume controls to the [speaker audio media player](https://esphome.io/components/media_player/speaker) component.

**Comment by Gutifarra** [comment]
Fully agree, the voice assistant is ridiculously loud if being used with external speakers and Music Assistant.

In the meanwhile, a quick and dirty workaround is to change the volume of the `media_player` when the assist is in state `processing`, and changing it back when it goes back to `idle`. 

The example below uses predefined volumes, you can set it to a % using templates. Since I have powered speakers plugged in I adjust the volume through there, as I've found it gets distorted anyways if I raise the assist volume past 80%.

```
alias: "Limit volume of bedroom response "
description: ""
triggers:
  - trigger: state
    entity_id:
      - assist_satellite.my_sat
    to: processing
    id: processing
  - trigger: state
    entity_id:
      - assist_satellite.my_sat
    to: idle
    id: idle
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - processing
        sequence:
          - action: media_player.volume_set
            metadata: {}
            data:
              volume_level: 0.6
            target:
              entity_id: media_player.my_sat
      - conditions:
          - condition: trigger
            id:
              - idle
        sequence:
          - action: media_player.volume_set
            metadata: {}
            data:
              volume_level: 0.8
            target:
              entity_id: media_player.my_sat
mode: single
```
