### ISSUE TITLE
Feature request: Play chime when a conversation is continued

### ISSUE THREAD

**Issue by Impact123** [esphome/home-assistant-voice-pe#375]
This makes it more obvious that it's listening and waiting for a response.

**Comment by tetele** [comment]
I'd use the wake word detected chime for consistency

**Comment by Akuka** [comment]
Until they will support if out of the box, this is a workaround:
```
alias: Play indication when Voice Assistant start Listening
triggers:
  - trigger: state
    entity_id:
      - assist_satellite.home_assistant_voice_XXX_assist_satellite
    from: null
    to: listening
conditions: []
actions:
  - action: media_player.play_media
    data:
      media_content_id: media-source://media_source/local/beep.mp3
      media_content_type: audio/mpeg
    target:
      entity_id: media_player.home_assistant_voice_XXX_media_player
mode: single
```
Its playing this sound indication also in the first time its start listening, Its a bit weird but better than nothing.


Im also using this automation to play sound indication when the conversation done:
```
alias: Play indication when Voice Assistant is Done
triggers:
  - trigger: state
    entity_id:
      - assist_satellite.home_assistant_voice_XXX_assist_satellite
    from: responding
    for:
      hours: 0
      minutes: 0
      seconds: 1
    to: idle
conditions: []
actions:
  - action: media_player.play_media
    data:
      media_content_id: media-source://media_source/local/end-call.mp3
      media_content_type: audio/mpeg
    target:
      entity_id: media_player.home_assistant_voice_XXX_media_player
mode: single
```
