### ISSUE TITLE
Internal speaker does not work

### ISSUE THREAD

**Issue by DRRDietrich** [esphome/home-assistant-voice-pe#379]
Since the last update, the internal speaker no longer works. Connecting an external speaker allows you to use the voice assistant normally again.

This is my setup.

ESPHome Configuration:
```yml
substitutions:
  name: home-assistant-kinderzimmer
  friendly_name: Home Assistant Kinderzimmer
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -100
      then:
       - light.turn_on:
           id: back_light
           brightness: 60%

api:
  encryption:
    key: ############################################

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret mobile_wifi_ssid
    password: !secret mobile_wifi_password

wireguard:
  address: 192.168.178.202
  private_key: ############################################
  peer_endpoint: ############################################
  peer_public_key: ############################################
  netmask: 255.255.255.0
  peer_port: #####
  peer_preshared_key: ############################################
  peer_allowed_ips:
    - 192.168.178.0/24
    - 0.0.0.0/0
  peer_persistent_keepalive: 25s

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

font:
  - file: 'digital-7.ttf'
    id: font_clock80
    size: 80
  - file: 'digital-7.ttf'
    id: font_clock60
    size: 60
  - file: 'digital-7.ttf'
    id: font_clock40
    size: 40
  - file: 'digital-7.ttf'
    id: font_clock32
    size: 32
  - file: 'BebasNeue-Regular.ttf'
    id: font80
    size: 80
  - file: 'BebasNeue-Regular.ttf'
    id: font60
    size: 60
  - file: 'BebasNeue-Regular.ttf'
    id: font50
    size: 50
  - file: 'BebasNeue-Regular.ttf'
    id: font32
    size: 32
  - file: 'digital-7.ttf'
    id: font3
    size: 80  
  - file: 'BebasNeue-Regular.ttf'
    id: font4
    size: 60
  - file: 'BebasNeue-Regular.ttf'
    id: font5
    size: 20
  - file: 'BebasNeue-Regular.ttf'
    id: font6
    size: 32

psram:
  mode: octal
  speed: 80MHz

spi:
  clk_pin: GPIO40
  mosi_pin: GPIO41

display:
  - platform: ili9xxx
    model: ST7735
    id: my_display
    dc_pin: GPIO01
    cs_pin: GPIO48
    reset_pin: GPIO42
    invert_colors: false
    color_palette: 8BIT
    rotation: 90
    dimensions:
      height: 160
      width: 128
      offset_width: 0
      offset_height: 0
    lambda: |-
      it.strftime(80, 0, id(font80), TextAlign::TOP_CENTER, "%H:%M", id(sntp_time).now());
      it.print(80, 80, id(font32), TextAlign::TOP_CENTER, "Kinderzimmer");

output:
  - platform: ledc
    pin: GPIO02
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Helligkeit"
    id: back_light
```
docker-compose.yml:
```yml
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ../music-assistant/media:/media
    restart: unless-stopped
    privileged: true
    network_mode: host
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
  music-assistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - "/etc/timezone:/etc/timezone:ro" 
      - ./music-assistant/data:/data/
      - ./music-assistant/media:/media/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model mobiuslabsgmbh/faster-whisper-large-v3-turbo --language de
    volumes:
      - ./whisper-data:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - 10300:10300
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice de_DE-thorsten-high
    volumes:
      - ./piper-data:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - 10200:10200
```
